"use client";
import { MenuItems } from "@/components/sidebar_menu/SideBarMenu";
import { MenuItem } from "@/types/MenuItemType";
import "./globals.css";
import OverrideMuiTheme from "@/theme/override";
import { Box } from "@mui/material";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body>
          <OverrideMuiTheme>
            <Box>{children}</Box>
          </OverrideMuiTheme>
        </body>
      </html>
    </>
  );
}
